#!/bin/bash
set -e

# Robust way to find project root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR/../"

echo "Running tests in $(pwd)"

# Install dependencies
python -m pip install -r .ci/requirements.txt --quiet
python -m pip install -r requirements.txt --quiet

# Run linting + tests
flake8 app/
pytest --verbose