name: Master CICD Pipeline

on:
  push:
    branches: main

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: login to GitHub Container Registry
        # https://github.com/docker/login-action
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker build . -t ghcr.io/${{ github.actor }}/example-cicd/my-example-fastapi-endpoint:$git_hash

      - name: Test the Docker image
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker run \
          --entrypoint=/bin/bash \
          ghcr.io/${{ github.actor }}/example-cicd/my-example-fastapi-endpoint:$git_hash \
          ./script/test

      - name: Login and push the Docker image to Github Packages
        run: |
          git_hash=$(git rev-parse --short HEAD)
          docker push ghcr.io/${{ github.actor }}/example-cicd/my-example-fastapi-endpoint:$git_hash

    # - name: Login to ECR
    #   # https://github.com/docker/login-action?tab=readme-ov-file#aws-elastic-container-registry-ecr
    #   uses: docker/login-action@v3
    #   with:
    #     registry: 516454187396.dkr.ecr.eu-west-3.amazonaws.com
    #     username: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    # - name: Login and push the Docker image to ECR
    #   run: |
    #     git_hash=$(git rev-parse --short HEAD)
    #     docker push 516454187396.dkr.ecr.eu-west-3.amazonaws.com/cedric/my-example-fastapi-endpoint:$git_hash

    # - name: Prepare SSH
    #   env:
    #     SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    #   run: |
    #     mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
    #     chmod 600 ~/.ssh/known_hosts
    #     ssh-keyscan {your_ec2_hostname_here} >> ~/.ssh/known_hosts
    #     eval $(ssh-agent)
    #     echo "$SSH_PRIVATE_KEY" > private_key.pem
    #     chmod 600 private_key.pem
    #     ssh-add private_key.pem

    # - name: SSH into EC2 machine
    #   run: |
    #     ssh -i private_key.pem ec2-user@{your_ec2_hostname_here} <<EOF
    #     // here you can write all the commands that need to be executed
    #     // on your EC2 machine
    #     EOF
